repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/bmorcos/pre-commit-hooks-cpp
    rev: 9a5aa38207bf557961110d6a4f7e3a9d352911f9
    hooks:
      - id: cpplint
        name: cpplint - pvl
        files: pvl
        args: [
          "--exclude=pvl/abridged",
          "--filter=-legal/copyright,-readability/alt_tokens,-whitespace/parens,-build/include_what_you_use,-runtime/int",
          "--linelength=62"
        ]
      - id: cpplint
        name: cpplint - tests
        files: tests
        args: [
          "--exclude=tests/build",
          "--filter=-legal/copyright,-readability/alt_tokens,-whitespace/parens,-build/include_what_you_use,-runtime/int,-build/include_order",
          "--linelength=80"
        ]
  - repo: https://github.com/psf/black
    rev: 21.10b0
    hooks:
      - id: black
        language_version: python3
